wget https://rubygems.org/downloads/backports-3.11.3.gem
wget https://rubygems.org/downloads/multi_json-1.13.1.gem
wget https://rubygems.org/downloads/open4-1.3.4.gem
wget https://rubygems.org/downloads/orderedhash-0.0.6.gem
wget https://rubygems.org/downloads/rack-protection-1.5.5.gem
wget https://rubygems.org/downloads/rack-test-0.7.0.gem
wget https://rubygems.org/downloads/rack-1.6.10.gem
wget https://rubygems.org/downloads/rpam-ruby19-1.2.1.gem
wget https://rubygems.org/downloads/sinatra-contrib-1.4.7.gem
wget https://rubygems.org/downloads/sinatra-1.4.8.gem
wget https://rubygems.org/downloads/tilt-2.0.8.gem
wget https://rubygems.org/downloads/ethon-0.11.0.gem
wget https://rubygems.org/downloads/ffi-1.9.25.gem
